apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: centos7
  namespace: runners
spec:
  replicas: 2
  template:
    spec:
      enterprise: ENTERPRISE-NAME-HERE
      ephemeral: true
      image: docker.GHE-HOSTNAME-HERE/goobernetes/centos7:latest
      imagePullPolicy: Always
      imagePullSecrets:
        - name: ghe
      dockerdWithinRunnerContainer: true
      dockerMTU: 1450
      resources:
        limits:
          cpu: "4000m"
          memory: "8Gi"
        requests:
          cpu: "200m"
          memory: "200Mi"
      labels:
      - docker
      - centos7
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: centos7-autoscaling
spec:
  scaleTargetRef:
    name: centos7
  minReplicas: 2
  maxReplicas: 6
  scaleDownDelaySecondsAfterScaleOut: 60
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.3'
    scaleUpFactor: '1.5'
    scaleDownFactor: '0.7'
