apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: rawhide-centos8
  namespace: runners
spec:
  replicas: 2
  template:
    spec:
      enterprise: ENTERPRISE-NAME-HERE
      ephemeral: false
      image: docker.GHE-HOSTNAME-HERE/goobernetes/centos8:latest
      imagePullPolicy: Always
      imagePullSecrets:
        - name: ghe
      dockerdWithinRunnerContainer: true
      dockerMTU: 1450
      resources:
        limits:
          cpu: "4000m"
          memory: "8Gi"
        requests:
          cpu: "200m"
          memory: "200Mi"
      labels:
      - rawhide-centos8
