apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: test-debian-bullseye
  namespace: test-runners
spec:
  replicas: 1
  template:
    spec:
      enterprise: ENTERPRISE-NAME-HERE
      ephemeral: true
      image: docker.GHE-HOSTNAME-HERE/goobernetes/debian-bullseye-test:latest
      imagePullPolicy: Always
      imagePullSecrets:
        - name: ghe
      dockerdWithinRunnerContainer: true
      dockerMTU: 1450
      resources:
        limits:
          cpu: "2000m"
          memory: "4Gi"
        requests:
          cpu: "200m"
          memory: "200Mi"
      labels:
      - test-debian-bullseye
