name: Build and push Debian Bullseye runner

on:
  push:
    branches:
    - main
    paths:
    - 'images/debian-bullseye.Dockerfile'
    - '.github/workflows/**-bullseye.yml'
    - 'images/**.sh'
    - 'images/docker/*'
    - 'images/patched/*'
    - 'images/software/*'
    - 'images/supervisor/*'

jobs:
  build:
    runs-on: [ bullseye ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.${{ secrets.GHE_HOSTNAME }}
          username: ${{ secrets.GHE_USERNAME }}
          password: ${{ secrets.GHE_TOKEN }}

      - name: Build the image
        run: |
          cd images
          docker build --network=host --file debian-bullseye.Dockerfile --tag docker.${{ secrets.GHE_HOSTNAME }}/goobernetes/debian-bullseye:latest .

      - name: Push to GitHub Packages
        run: docker push docker.${{ secrets.GHE_HOSTNAME }}/goobernetes/debian-bullseye:latest
