name: Rawhide - remove CentOS 7 deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Remove the rawhide CentOS 7 deployment
    runs-on: [ centos7 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Write out the kubeconfig info
        run: | 
          echo ${{ secrets.PROD_RUNNER_DEPLOY }} | base64 -d > /tmp/config

      - name: Deploy
        run: |
          kubectl delete -f runners/rawhide-centos7.yml
        env:
          KUBECONFIG: /tmp/config

      - name: Remove kubeconfig info
        run: rm -f /tmp/config
