name: Build and publish Debian Buster runner

on:
  schedule:
    - cron: '15 3 1 * *'  # build once a week unless needed to more frequently
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'images/debian-buster.Dockerfile'
    - '.github/workflows/**-buster.yml'
    - 'images/**.sh'
    - 'images/docker/*'
    - 'images/patched/*'
    - 'images/software/*'
    - 'images/supervisor/*'

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build the image
        run: |
          cd images
          docker build --network=host --file debian-buster.Dockerfile --tag ghcr.io/boozallen/goobernetes/debian-buster:latest .

      - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
        uses: anchore/scan-action@main
        with:
          image: "ghcr.io/boozallen/goobernetes/debian-buster:latest"
          fail-build: false
          acs-report-enable: true

      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif

      - name: Generate SBOM for the Debian Buster (10) runner
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/boozallen/goobernetes/debian-buster:latest

      - name: Push to GitHub Packages
        run: docker push ghcr.io/boozallen/goobernetes/debian-buster:latest
