name: Build and publish Ubuntu Focal runner

on:
  schedule:
    - cron: '15 3 1 * *'  # build once a week unless needed to more frequently
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'images/ubuntu-focal.Dockerfile'
    - '.github/workflows/**-focal.yml'
    - 'images/**.sh'
    - 'images/docker/*'
    - 'images/patched/*'
    - 'images/software/*'
    - 'images/supervisor/*'

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build the image
        run: |
          cd images
          docker build --network=host --file ubuntu-focal.Dockerfile --tag ghcr.io/boozallen/goobernetes/ubuntu-focal:latest .

      - name: Push to GitHub Packages
        run: docker push ghcr.io/boozallen/goobernetes/ubuntu-focal:latest
