name: Generate SBOM for each image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  centos7-sbom:
    runs-on: ubuntu-latest
    steps:
    - name: Generate SBOM for the CentOS 7 runner
      uses: anchore/sbom-action@v0
      with:
        image: ghcr.io/boozallen/goobernetes/centos7-runner:latest

  centos8-sbom:
    runs-on: ubuntu-latest
    steps:
    - name: Generate SBOM for the CentOS 8 runner
      uses: anchore/sbom-action@v0
      with:
        image: ghcr.io/boozallen/goobernetes/centos8-runner:latest

  debian-buster-sbom:
    runs-on: ubuntu-latest
    steps:
    - name: Generate SBOM for the Debian Buster (10) runner
      uses: anchore/sbom-action@v0
      with:
        image: ghcr.io/boozallen/goobernetes/debian-buster:latest

  debian-bullseye-sbom:
    runs-on: ubuntu-latest
    steps:
    - name: Generate SBOM for the Debian Bullseye (11) runner
      uses: anchore/sbom-action@v0
      with:
        image: ghcr.io/boozallen/goobernetes/debian-bullseye:latest

  ubuntu-focal-sbom:
    runs-on: ubuntu-latest
    steps:
    - name: Generate SBOM for the Ubuntu Focal (20.04 LTS) runner
      uses: anchore/sbom-action@v0
      with:
        image: ghcr.io/boozallen/goobernetes/ubuntu-focal:latest
